import { NextRequest, NextResponse } from 'next/server'
import fs from 'fs/promises'
import path from 'path'

export async function POST(request: NextRequest) {
  try {
    const { workspacePath, configPath } = await request.json()

    if (!workspacePath || !configPath) {
      return NextResponse.json(
        { error: 'Workspace path and config path are required' },
        { status: 400 }
      )
    }

    // Validate paths exist
    try {
      await fs.access(workspacePath)
    } catch {
      return NextResponse.json(
        { error: `Workspace path does not exist: ${workspacePath}` },
        { status: 400 }
      )
    }

    try {
      await fs.access(configPath)
    } catch {
      return NextResponse.json(
        { error: `Config path does not exist: ${configPath}` },
        { status: 400 }
      )
    }

    // Create .env.local
    const envContent = `# Mission Control Configuration
# Generated by setup wizard on ${new Date().toISOString()}

# OpenClaw Integration
OPENCLAW_WORKSPACE=${workspacePath}
OPENCLAW_CONFIG=${configPath}

# Data Directory
DATA_DIR=./data

# Next.js Configuration
NEXT_PUBLIC_APP_URL=http://localhost:3000

# Development
NODE_ENV=development
`

    const projectRoot = process.cwd()
    const envPath = path.join(projectRoot, '.env.local')

    await fs.writeFile(envPath, envContent, 'utf-8')

    return NextResponse.json({
      success: true,
      message: 'Setup completed successfully',
      envPath: envPath
    })

  } catch (error) {
    console.error('Setup API Error:', error)
    return NextResponse.json(
      { error: 'Setup failed', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    )
  }
}